import Head from 'next/head'
// import styles from '../styles/Home.module.css'
import Footer from '../components/Footer';
import dynamic from 'next/dynamic';
import Stats from '../components/Stats';
import Stats2 from '../components/Stats2';
import StolenChart from '../components/StolenChart';
import SpamContracts from '../components/SpamContracts';
import React from "react";

const Header = dynamic(() => import('../components/Header'), {
  ssr: false,
})

export default function Home() {
  const [tab, setTab] = React.useState(true);

  const setState = (state) => {
    setTab(state);
  }

  return (
    <div className="min-h-screen bg-base-200" data-theme="fantasy">
      <Head>
        <title>Metamorphosis Data visualization</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className='min-h-screen'>

        <div className="tabs tabs-boxed justify-center m-10">
          <a className={tab ? "tab tab-lg tab-active" : "tab tab-lg"} onClick={(e) => setState(true)}>Stolen NFTs</a>
          <a className={tab ? "tab tab-lg" : "tab tab-lg tab-active"} onClick={(e) => setState(false)}>Spam Contracts</a>
        </div>


        <div className="hero">
          {tab ? (<Stats />) : (<Stats2 />)}
        </div>

        <div className='w-scree mt-10'>
          {tab ? (<StolenChart />) : (<SpamContracts />)}
        </div>

      </div>
      <Footer />
    </div >
  )
}
